services:
  kusto:
    container_name: kusto
    hostname: kusto
    image: mcr.microsoft.com/azuredataexplorer/kustainer-linux
    volumes:
      - type: bind
        source: ./docker/kustodata
        target: /kustodata
        bind:
          create_host_path: false
      - type: bind
        source: ./docker/kustainer_cert
        target: /kustainer_cert
        bind:
          create_host_path: false
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - kusto_network
    restart: always
    environment:
      - ACCEPT_EULA=Y
  # Optional Jupyter service for interactive querying
  jupyter:
    container_name: jupyter
    hostname: jupyter
    image: jupyter/minimal-notebook:x86_64-python-3.11.6
    volumes:
      - type: bind
        source: ./docker/jupyter
        target: /home/jovyan/100-days-of-kql
        bind:
          create_host_path: false
    ports:
      - 127.0.0.1:8888:8888
    networks:
      - kusto_network
    restart: always
  caddy:
    container_name: caddy
    hostname: localfiles
    image: caddy:2.11.2-alpine
    volumes:
      - type: bind
        source: ./docker/caddy
        target: /etc/caddy
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ./samples
        target: /srv
        read_only: true
        bind:
          create_host_path: false
    ports:
      - 127.0.0.1:4433:443
    networks:
      - kusto_network
    restart: always

networks:
  kusto_network:
    driver: bridge
    name: kusto_workspace
